---
version: "3"
services:
  mysql:
    image: mysql:5
    container_name: rest_mysql
    hostname: rest_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
      # MYSQL_USER: 'root'
    networks:
      - restaurant

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - restaurant

networks:
  restaurant:
    driver: bridge
  default:
    external:
      name: restaurant
