---
version: "3"
services:
  order:
    image: ythalorossy/order:1.0.0
    container_name: order
    hostname: order
    ports:
      - "8100:8080"
    environment: 
      - "SPRING_DATASOURCE_URL=jdbc:mysql://rest_mysql:3306/restaurant?createDatabaseIfNotExist=true"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=my-secret-pw"
    networks:
      - restaurant

  payment:
    image: ythalorossy/payment:1.0.0
    container_name: payment
    hostname: payment
    ports:
      - "8200:8080"
    networks:
      - restaurant
    depends_on:
      - order

  restaurant:
    image: ythalorossy/restaurant:1.0.0
    container_name: restaurant
    hostname: restaurant
    ports:
      - "8300:8080"
    networks:
      - restaurant
    depends_on:
      - payment

networks:
  restaurant:
    driver: bridge
  default:
    external:
      name: restaurant
