server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10000
      routes:
      - id: order
        uri: http://localhost:8100/
        predicates:
        - Path=/order/**
      - id: payment
        uri: http://localhost:8200/
        predicates:
        - Path=/payment/**
      - id: restaurant
        uri: http://localhost:8300/
        predicates:
        - Path=/restaurant/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
          

